return {
  ["famiu/bufdelete.nvim"] = { disable = true },
  ["goolord/alpha-nvim"] = { disable = false },
  ["lukas-reineke/indent-blankline.nvim"] = { disable = false },
  ["max397574/better-escape.nvim"] = { disable = false },
  ["numToStr/Comment.nvim"] = { disable = false },
  ["EdenEast/nightfox.nvim"] = require "user.plugins.nightfox",
  ["danymat/neogen"] = require "user.plugins.neogen",
  ["echasnovski/mini.nvim"] = require "user.plugins.mini",
  ["ethanholz/nvim-lastplace"] = require "user.plugins.nvim-lastplace",
  ["folke/zen-mode.nvim"] = require "user.plugins.zen-mode",
  ["hrsh7th/cmp-calc"] = require "user.plugins.cmp-calc",
  ["hrsh7th/cmp-emoji"] = require "user.plugins.cmp-emoji",
  ["jose-elias-alvarez/typescript.nvim"] = require "user.plugins.typescript",
  ["lukas-reineke/headlines.nvim"] = require "user.plugins.headlines",
  ["mfussenegger/nvim-dap"] = require "user.plugins.dap",
  ["mtikekar/nvim-send-to-term"] = require "user.plugins.nvim-send-to-term",
  ["nvim-telescope/telescope-file-browser.nvim"] = require "user.plugins.telescope-file-browser",
  ["nvim-telescope/telescope-hop.nvim"] = require "user.plugins.telescope-hop",
  ["nvim-telescope/telescope-media-files.nvim"] = require "user.plugins.telescope-media-files",
  ["nvim-telescope/telescope-project.nvim"] = require "user.plugins.telescope-project",
  ["nvim-treesitter/nvim-treesitter-textobjects"] = require "user.plugins.nvim-treesitter-textobjects",
  ["phaazon/hop.nvim"] = require "user.plugins.hop",
  ["rcarriga/nvim-dap-ui"] = require "user.plugins.dapui",
  ["ziontee113/syntax-tree-surfer"] = require "user.plugins.syntax-tree-surfer",
  ["akinsho/git-conflict.nvim"] = require "user.plugins.git-conflict",
  ["ur4ltz/surround.nvim"] = {
    event = "BufRead",
    config = function() require("surround").setup { mappings_style = "surround", map_insert_mode = false } end,
  },
  ["sindrets/diffview.nvim"] = {},
  ["mfussenegger/nvim-jdtls"] = {},
  ["sainnhe/gruvbox-material"] = {},
}
